/* =====================================================================
   FLEXCPP™ — Grade data (single source of truth)
   Real specifications transcribed from flexfilm.com Technical Data Sheets
   (TDS PDFs: /pdf/Products/CPP/*.pdf). Bilingual RU / EN.
   ===================================================================== */
window.GRADES = [
  {
    code:"C-CPM", accent:"met",
    tag:{ru:"МЕТАЛЛИЗИРУЕМАЯ", en:"METALLIZABLE"},
    name:{ru:"Металлизируемая CPP", en:"Metallizable CPP film"},
    thk:"20–50", sit:"118", seal:"1700–2500", density:"0.91", treat:"38",
    desc:{ru:"Соэкструдированная прозрачная база под металлизацию: одна сторона обработана, другая — термосвариваемая.",
          en:"Co-extruded transparent metallizable base film — one side treated, the other heat-sealable."},
    structure:{ru:["Металлоприёмный слой","Промежуточный слой","CPP-ядро","Промежуточный слой","Термослой · SIT 118°C"],
               en:["Metal-receptive layer","Inter layer","CPP core layer","Inter layer","Heat-seal layer · SIT 118°C"]},
    features:{ru:["Превосходная адгезия металла","Отличная свариваемость","Высокая машинопригодность","Яркий металлический блеск"],
              en:["Superior metal anchorage","Excellent sealing strength","Excellent machinability","Brilliant metallic gloss"]},
    apps:{ru:["Базовая плёнка под металлизацию","Печать после металлизации","Снеки · кондитерка · выпечка"],
          en:["Base film for metallization","Printable after metallization","Snacks · confectionery · bakery"]}
  },
  {
    code:"C-CLL", accent:"sit",
    tag:{ru:"УЛЬТРА-НИЗКАЯ SIT", en:"ULTRA-LOW SIT"},
    name:{ru:"Прозрачная · ультра-низкая SIT", en:"Transparent · ultra-low SIT"},
    thk:"15–50", sit:"90", seal:"1500–2600", density:"0.91", treat:"38",
    desc:{ru:"Прозрачная CPP с инженерным термослоем: ультра-низкая SIT, широкое окно сварки и высокий горячий захват.",
          en:"Transparent CPP engineered for ultra-low SIT, a broad sealing window and high hot-tack."},
    structure:{ru:["Обработанный слой","Промежуточный слой","CPP-ядро","Промежуточный слой","Ультра-низкий SIT · 90°C"],
               en:["Treated layer","Inter layer","CPP core layer","Inter layer","Ultra-low SIT seal · 90°C"]},
    features:{ru:["Ультра-низкая SIT, широкое окно сварки","Высокий и широкий горячий захват","Отличная герметичность шва","Стабильность на высоких скоростях"],
              en:["Ultra-low SIT, broad sealing range","High & broad hot-tack","Excellent seal hermeticity","Stable at high line speeds"]},
    apps:{ru:["Снеки и кондитерские изделия","Высокоскоростные HFFS / VFFS линии"],
          en:["Snacks & confectionery packaging","High-speed HFFS / VFFS machines"]}
  },
  {
    code:"C-CHL", accent:"sit",
    tag:{ru:"НИЗКАЯ SIT · ПРОЧНЫЙ ШОВ", en:"LOW SIT · STRONG SEAL"},
    name:{ru:"Прозрачная · низкая SIT, прочный шов", en:"Transparent · low SIT, high seal strength"},
    thk:"20–25", sit:"108", seal:"2200", density:"0.91", treat:"38",
    desc:{ru:"Прозрачная CPP с низкой SIT, широким окном сварки и высоким горячим захватом для прочного герметичного шва.",
          en:"Transparent CPP with low SIT, broad sealing range and high hot-tack for a strong hermetic seal."},
    structure:{ru:["Обработанный слой","Промежуточный слой","CPP-ядро","Промежуточный слой","Термослой · SIT 108°C"],
               en:["Treated layer","Inter layer","CPP core layer","Inter layer","Heat-seal layer · SIT 108°C"]},
    features:{ru:["Низкая SIT, широкое окно сварки","Высокий и широкий горячий захват","Отличная герметичность","Высокая прочность шва"],
              en:["Low SIT, broad sealing range","High & broad hot-tack","Excellent hermeticity","High seal strength"]},
    apps:{ru:["Соусы и приправы","Высокоскоростные FFS линии"],
          en:["Condiment & sauce packaging","High-speed FFS machines"]}
  },
  {
    code:"C-CWL", accent:"white",
    tag:{ru:"БЕЛАЯ НЕПРОЗР.", en:"WHITE OPAQUE"},
    name:{ru:"Белая непрозрачная CPP", en:"White opaque CPP film"},
    thk:"18–40", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Соэкструдированная белая непрозрачная плёнка: одна сторона корона-обработана, другая — свариваемая.",
          en:"Co-extruded white opaque film — one side corona-treated, the other sealable."},
    structure:{ru:["Обработанный слой","Белое непрозрачное ядро","Термосвариваемый слой"],
               en:["Treated layer","White opaque core","Heat-seal layer"]},
    features:{ru:["Высокий блеск и улучшенная непрозрачность","Белизна исключает белую краску","Стабильное скольжение","Отличная герметичность шва"],
              en:["High gloss & improved opacity","Whiteness eliminates white ink","Consistent slip","Excellent seal integrity"]},
    apps:{ru:["Ламинация и конвертинг","Кондитерка · оверрап · поверхностная печать"],
          en:["Lamination & conversion","Confectionery · overwrap · surface printing"]}
  },
  {
    code:"C-CWU", accent:"white",
    tag:{ru:"БЕЛАЯ · НИЗКАЯ SIT", en:"WHITE · LOW SIT"},
    name:{ru:"Белая непрозрачная · низкая SIT", en:"White opaque · low SIT"},
    thk:"22–40", sit:"низкая", sit_en:"low", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Соэкструдированная белая непрозрачная плёнка с низкой SIT для надёжной скоростной упаковки.",
          en:"Co-extruded low-SIT white opaque film for reliable high-speed packaging."},
    structure:{ru:["Обработанный слой","Белое непрозрачное ядро","Низкий SIT термослой"],
               en:["Treated layer","White opaque core","Low-SIT heat-seal layer"]},
    features:{ru:["Низкая SIT","Отличная герметичность шва","Высокая целостность шва","Отличный горячий захват"],
              en:["Low SIT","Excellent seal hermeticity","Excellent seal integrity","Excellent hot-tack"]},
    apps:{ru:["Ламинация и конвертинг","Печенье и снеки"],
          en:["Lamination & conversion","Biscuit & snack packaging"]}
  },
  {
    code:"C-MNC", accent:"matt",
    tag:{ru:"МАТОВАЯ", en:"MATT"},
    name:{ru:"Матовая CPP · soft-touch", en:"Matt CPP · soft-touch"},
    thk:"25–38", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Матовая CPP с обогащённой эстетикой и бумажно-тактильным ощущением; одна или обе стороны обработаны.",
          en:"Matt-finish CPP with enriched aesthetics and a paper-like feel; one- or both-side treated."},
    structure:{ru:["Матовый внешний слой","CPP-ядро","Свариваемый / обработанный слой"],
               en:["Matt outer layer","CPP core layer","Seal / treated layer"]},
    features:{ru:["Премиальный матовый soft-touch","Хорошая контактная прозрачность","Чёткая печатная графика","Антистатик и скольжение"],
              en:["Premium matt soft-touch","Good contact clarity","Sharp print graphics","Good antistatic & slip"]},
    apps:{ru:["Высокоскоростные упаковочные машины","Премиум-сегмент · дой-пак"],
          en:["High-speed packaging machines","Premium segment · stand-up pouch"]}
  },
  {
    code:"C-CDF", accent:"freeze",
    tag:{ru:"ГЛУБОКАЯ ЗАМОРОЗКА", en:"DEEP-FREEZE"},
    name:{ru:"CPP для глубокой заморозки", en:"Deep-freeze CPP film"},
    thk:"25–40", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Модифицированная прозрачная плёнка, свариваемая с обеих сторон, для условий глубокой заморозки.",
          en:"Modified transparent film, both-side sealable, engineered for deep-freeze conditions."},
    structure:{ru:["Обработанный слой","CPP-ядро (заморозка)","Свариваемый слой"],
               en:["Treated layer","Deep-freeze CPP core","Heat-seal layer"]},
    features:{ru:["Отличные свойства глубокой заморозки","Высокая ударная прочность","Хорошие оптические свойства","Стабильность на высоких скоростях"],
              en:["Excellent deep-freeze properties","High drop-impact strength","Good optical properties","Stable at high speeds"]},
    apps:{ru:["Заморозка · мороженое","Хлеб · выпечка · замор. продукты"],
          en:["Frozen foods · ice cream","Bread · bakery · frozen products"]}
  },
  {
    code:"C-CPR", accent:"retort",
    tag:{ru:"РЕТОРТ / СТЕРИЛИЗАЦИЯ", en:"RETORT / STERILIZE"},
    name:{ru:"Реторт-CPP", en:"Retort CPP film"},
    thk:"60 / 70", sit:"", seal:"высокая", seal_en:"high", density:"0.91", treat:"38",
    desc:{ru:"Прозрачная CPP с обработкой под асептическую / реторт-упаковку и стерилизацию при высоких температурах.",
          en:"Transparent CPP treated for aseptic / retort packaging and high-temperature sterilization."},
    structure:{ru:["Обработанный слой","Реторт CPP-ядро","Свариваемый слой"],
               en:["Treated layer","Retort CPP core","Heat-seal layer"]},
    features:{ru:["Отличная стерилизуемость","Высокая адгезия клея при ламинации","Высокая прочность шва"],
              en:["Excellent sterilization performance","Strong lamination adhesive anchorage","High seal strength"]},
    apps:{ru:["Стерилизация и пастеризация","Горячий розлив · готовые блюда"],
          en:["Sterilization & pasteurization","Hot-fill · ready-to-eat meals"]}
  },
  {
    code:"C-CBP", accent:"plain",
    tag:{ru:"2-СТОР. СВАРКА", en:"BOTH-SIDE SEAL"},
    name:{ru:"Двусторонне свариваемая CPP", en:"Both-side sealable CPP"},
    thk:"20–40", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Соэкструдированная CPP, корона-обработанная с одной стороны и свариваемая с обеих сторон.",
          en:"Co-extruded CPP, corona-treated on one side and heat-sealable on both sides."},
    structure:{ru:["Обработанный / свариваемый слой","CPP-ядро","Свариваемый слой"],
               en:["Treated / sealable layer","CPP core layer","Heat-seal layer"]},
    features:{ru:["Хорошие оптические свойства","Низкое скольжение для скорости","Отличная машинопригодность","Отличный горячий захват"],
              en:["Good optical properties","Low slip for high speed","Excellent machinability","Excellent hot-tack"]},
    apps:{ru:["Ламинация и однослойное применение","Прямая упаковка: паста, выпечка","Джамбо-паки (снеки)"],
          en:["Lamination & single-ply use","Direct food packing: pasta, bakery","Jumbo packs (snacks)"]}
  },
  {
    code:"C-CPT", accent:"twist",
    tag:{ru:"ТВИСТ-УПАКОВКА", en:"TWIST WRAP"},
    name:{ru:"Твист-CPP", en:"Twist-wrap CPP film"},
    thk:"25–35", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Модифицированная прозрачная плёнка с обработкой под твист-применение (закрутка обёртки).",
          en:"Modified transparent film treated for twist-wrap applications."},
    structure:{ru:["Обработанный слой","CPP-ядро (твист)","Внутренний слой"],
               en:["Treated layer","Twist CPP core","Inner layer"]},
    features:{ru:["Отличный блеск и жёсткость","Отличная закручиваемость (твист)","Превосходная печатаемость"],
              en:["Excellent gloss & stiffness","Excellent twistability","Superior printability"]},
    apps:{ru:["Твист-обёртка · обёртка конфет","Кондитерский конвертинг"],
          en:["Twist wrap · candy wrap","Confectionery conversion"]}
  },
  {
    code:"C-CKP", accent:"plain",
    tag:{ru:"ТЕРМОСТОЙКАЯ", en:"HIGH HEAT"},
    name:{ru:"Термостойкая CPP", en:"High-heat-resistance CPP"},
    thk:"40", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Специальная прозрачная CPP с высоким блеском, хорошей печатаемостью и термостойкостью необработанной стороны.",
          en:"Specially designed plain CPP with high gloss, good printability and high heat resistance on the untreated side."},
    structure:{ru:["Высокоглянцевый слой","CPP-ядро","Термостойкий слой"],
               en:["High-gloss layer","CPP core layer","Heat-resistant layer"]},
    features:{ru:["Хорошие оптические свойства","Хорошая печатаемость","Высокая термостойкость","Хорошая машинопригодность"],
              en:["Good optics","Good printability","High heat resistance","Good machinability"]},
    apps:{ru:["Кондитерская упаковка"],
          en:["Confectionery packaging"]}
  },
  {
    code:"C-CPA", accent:"antifog",
    tag:{ru:"АНТИФОГ", en:"ANTI-FOG"},
    name:{ru:"Антифог CPP", en:"Anti-fog CPP film"},
    thk:"40–50", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Плёнка с антифог-обработкой (холодный и горячий) с одной стороны и термосвариваемой — с другой.",
          en:"Film with anti-fog (cold & hot) treated layer on one side and heat-sealable layer on the other."},
    structure:{ru:["Антифог обработанный слой","CPP-ядро","Свариваемый слой"],
               en:["Anti-fog treated layer","CPP core layer","Heat-seal layer"]},
    features:{ru:["Отличный горячий захват и сварка","Стабильное скольжение","Хороший блеск и жёсткость","Хорошие антифог-свойства"],
              en:["Excellent hot-tack & sealing","Consistent slip","Good gloss & stiffness","Good anti-fog properties"]},
    apps:{ru:["Свежие овощи и фрукты","Салаты · мясо"],
          en:["Fresh vegetables & fruits","Salad · meat packaging"]}
  },
  {
    code:"C-CPL", accent:"plain",
    tag:{ru:"ЛАМИНАЦИЯ", en:"LAMINATION"},
    name:{ru:"CPP для ламинации", en:"Lamination CPP film"},
    thk:"15–80", sit:"", seal:"", density:"0.91", treat:"38",
    desc:{ru:"Соэкструдированная прозрачная плёнка: одна сторона корона-обработана, другая — свариваемая.",
          en:"Co-extruded transparent film — one side corona-treated, the other sealable."},
    structure:{ru:["Обработанный слой","CPP-ядро","Свариваемый слой"],
               en:["Treated layer","CPP core layer","Heat-seal layer"]},
    features:{ru:["Хорошие оптические свойства","Стабильное скольжение","Хорошая машинопригодность","Хороший горячий захват"],
              en:["Good optics","Consistent slip","Good machinability","Good hot-tack"]},
    apps:{ru:["Ламинационное применение","Упаковка пасты"],
          en:["Lamination applications","Pasta packaging"]}
  }
];
